### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by shwangdev** [zuisong/gemini-openai-proxy#63]
Check below error message:

```
Error: [500 Internal Server Error] An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting
    at makeRequest (file:///root/gemini-openai-proxy/dist/main_node.mjs:914:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContent (file:///root/gemini-openai-proxy/dist/main_node.mjs:880:20)
    at async streamingChatProxyHandler (file:///root/gemini-openai-proxy/dist/main_node.mjs:1020:22)
    at async file:///root/gemini-openai-proxy/dist/main_node.mjs:1078:24
    at async Object.pull (file:///root/gemini-openai-proxy/dist/main_node.mjs:1091:31)
```

**Comment by zuisong** [comment]
Is this issue occurring 100% of the time?
It seems like the error might be an internal issue with Google Gemini.


Could you provide the request body？

**Comment by shwangdev** [comment]
No, this issue happens occasionally.

How can I get the request body?

**Comment by zuisong** [comment]
The problems can be considered as problems with Google gemini service. 
I have encountered them before. Generally, you can try again.
