### ISSUE TITLE
Error: [400 Bad Request] Invalid JSON payload received. Unknown name "$schema" 

### ISSUE THREAD

**Issue by StevenTruong89** [zuisong/gemini-openai-proxy#67]
Hi zuizong,

I'm facing below issue, you please help me to take a look if have free time. Thank you so much

`
2024-08-06T10:03:58.433Z WARN 2adc933d-95c5-4fd6-bc2c-53223dd551d3 <-- POST http://10.20.95.28:8000/v1/chat/completions
Error: [400 Bad Request] Invalid JSON payload received. Unknown name "$schema" at 'tools[0].function_declarations[0].parameters': Cannot find field.
Invalid JSON payload received. Unknown name "additionalProperties" at 'tools[0].function_declarations[0].parameters': Cannot find field.
Invalid JSON payload received. Unknown name "$schema" at 'tools[0].function_declarations[1].parameters': Cannot find field.
Invalid JSON payload received. Unknown name "additionalProperties" at 'tools[0].function_declarations[1].parameters': Cannot find field.
Invalid JSON payload received. Unknown name "$schema" at 'tools[0].function_declarations[2].parameters': Cannot find field.
Invalid JSON payload received. Unknown name "additionalProperties" at 'tools[0].function_declarations[2].parameters': Cannot find field. [{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"tools[0].function_declarations[0].parameters","description":"Invalid JSON payload received. Unknown name \"$schema\" at 'tools[0].function_declarations[0].parameters': Cannot find field."},{"field":"tools[0].function_declarations[0].parameters","description":"Invalid JSON payload received. Unknown name \"additionalProperties\" at 'tools[0].function_declarations[0].parameters': Cannot find field."},{"field":"tools[0].function_declarations[1].parameters","description":"Invalid JSON payload received. Unknown name \"$schema\" at 'tools[0].function_declarations[1].parameters': Cannot find field."},{"field":"tools[0].function_declarations[1].parameters","description":"Invalid JSON payload received. Unknown name \"additionalProperties\" at 'tools[0].function_declarations[1].parameters': Cannot find field."},{"field":"tools[0].function_declarations[2].parameters","description":"Invalid JSON payload received. Unknown name \"$schema\" at 'tools[0].function_declarations[2].parameters': Cannot find field."},{"field":"tools[0].function_declarations[2].parameters","description":"Invalid JSON payload received. Unknown name \"additionalProperties\" at 'tools[0].function_declarations[2].parameters': Cannot find field."}]}]
    at makeRequest (file:///data/app.mjs:490:13)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async generateContent (file:///data/app.mjs:456:20)
    at async streamingChatProxyHandler (file:///data/app.mjs:596:22)
    at async file:///data/app.mjs:654:24
    at async Object.pull (file:///data/app.mjs:667:31)
`

**Comment by StevenTruong89** [comment]
![image](https://github.com/user-attachments/assets/d8f795cb-1ef0-4cb9-92b6-af089653c047)

I'm using docker for desktop

**Comment by zuisong** [comment]
It will be better if you can provide your request body😃
